name: Daily Weather Update

on:
  schedule:
    - cron: '0 8 * * *'  # Every day at 08:00 UTC
  workflow_dispatch:

jobs:
  scrape:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: pip install requests beautifulsoup4

      - name: Run scraper
        run: python scraper.py

      - name: Commit watering data
        run: |
          git config user.name "github-actions"
          git config user.email "actions@github.com"
          git add data/weather_data.json
          git commit -m "Update watering data [skip ci]" || echo "No changes"
          git push
